apiVersion: v1
kind: Service
metadata:
  name: @project.build.finalName@-service
  labels:
    name: @project.build.finalName@-service
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: @project.build.finalName@
